# Development override cho docker-compose.yml
# Sử dụng: docker compose -f docker-compose.yml -f docker-compose.dev.yml up
services:
  emlinh_app:
    build:
      target: production  # Vẫn dùng production target nhưng với dev settings
    environment:
      - FLASK_ENV=development
      - DEBUG=true
      - SQLALCHEMY_ECHO=true
      # Có thể sử dụng cùng PostgreSQL service: postgresql://emlinh_user:emlinh_password@postgres:5432/emlinh_db
      - DATABASE_URL=postgresql://dev_user:dev_password@192.168.1.10:5432/emlinh_dev_db
      - OLLAMA_BASE_URL=http://192.168.1.10:11434
    volumes:
      # Mount source code để hot reload
      - ./emlinh_mng:/app/emlinh_mng
      - ./emlinh-remotion:/app/emlinh-remotion
    ports:
      - "5000:5000"  # Flask development server
      - "3000:3000"  # Remotion studio
      - "8080:8080"  # Additional debug port

  # Override nginx với development config
  nginx:
    # Disable nginx trong dev mode để truy cập trực tiếp
    profiles: ["production"]
