version: '3.8'

# Development override cho docker-compose.yml
services:
  emlinh_app:
    build:
      target: production  # Vẫn dùng production target nhưng với dev settings
    environment:
      - FLASK_ENV=development
      - DEBUG=true
      - SQLALCHEMY_ECHO=true
    volumes:
      # Mount source code để hot reload
      - ./emlinh_mng:/app/emlinh_mng
      - ./emlinh-remotion:/app/emlinh-remotion
    ports:
      - "5000:5000"  # Flask development server
      - "3000:3000"  # Remotion studio
      - "8080:8080"  # Additional debug port

  # Override nginx với development config
  nginx:
    # Disable nginx trong dev mode để truy cập trực tiếp
    profiles: ["production"]

  # Lightweight DB cho development
  postgres:
    environment:
      POSTGRES_DB: emlinh_dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"  # Expose port cho external tools
